### ISSUE TITLE
Review Documentation of Volumes

### ISSUE THREAD

**Issue by jpthurman** [UffizziCloud/docs#79]

**Comment by jpthurman** [comment]
Follow-up Action to https://github.com/UffizziCloud/uffizzi_platform/issues/430

1. Are we explaining volumes / non-empty volumes at a high level?
2. How does a user find this information?
3. Is related information appropriately linked?
4. Are there appropriate examples in a compose reference?
5. Is the implementation described in enough detail that a user can understand capabilities / limitations

**Comment by gadkins** [comment]
As discussed, our support for volumes is as follows:
- We support volumes <1MB because we use ConfigMaps for the compressed file, which has a limitation of 1MB
- The compressed file is stored in our database because it needs to be stored somewhere. We should avoid storing larger volumes in our database as it is not best practice.
- When uncompressing, we store the volume via Persistent Volume Claim (PVC), which is only limited in size by the underlying google cloud node storage
- Each container that mounts a volume may have read+write access to it (or optionally read-only access) — this solves many use cases including wordpress and any application that has a producer/consumer architecture
- We will not support keywords :delegated or :cached since they are intended to improve i/o performance; this is not relevant in the context of K8s
- We will delay implementing support for [larger volumes](https://github.com/UffizziCloud/uffizzi_platform/issues/394) since we have not encountered projects for which there is no workaround
When we implement support for large volumes, it is likely that we use object storage

**Comment by gadkins** [comment]
Implemented here https://github.com/UffizziCloud/docs/commit/ccaf153c308ec5cd5f448f79a980e013cfa323c6
